Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Map = geemap.Map(height=800,width=700,center=[52.37,4.5],zoom=7)
Map
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/data.py:221[0m, in [0;36mget_persistent_credentials[0;34m()[0m
[1;32m    220[0m [38;5;28;01mtry[39;00m:
[0;32m--> 221[0m   [38;5;28;01mreturn[39;00m Credentials([38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39m[43moauth[49m[38;5;241;43m.[39;49m[43mget_credentials_arguments[49m[43m([49m[43m)[49m)
[1;32m    222[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIOError[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/oauth.py:74[0m, in [0;36mget_credentials_arguments[0;34m()[0m
[1;32m     73[0m [38;5;28;01mdef[39;00m [38;5;21mget_credentials_arguments[39m():
[0;32m---> 74[0m   [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mget_credentials_path[49m[43m([49m[43m)[49m[43m)[49m [38;5;28;01mas[39;00m creds:
[1;32m     75[0m     stored [38;5;241m=[39m json[38;5;241m.[39mload(creds)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/runner/.config/earthengine/credentials'

During handling of the above exception, another exception occurred:

[0;31mEEException[0m                               Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/geemap/common.py:227[0m, in [0;36mee_initialize[0;34m(token_name, auth_mode, service_account)[0m
[1;32m    225[0m                 copy_credentials_to_drive()
[0;32m--> 227[0m     [43mee[49m[38;5;241;43m.[39;49m[43mInitialize[49m[43m([49m[43mhttp_transport[49m[38;5;241;43m=[39;49m[43mhttplib2[49m[38;5;241;43m.[39;49m[43mHttp[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    228[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/__init__.py:131[0m, in [0;36mInitialize[0;34m(credentials, opt_url, cloud_api_key, http_transport, project)[0m
[1;32m    130[0m [38;5;28;01mif[39;00m credentials [38;5;241m==[39m [38;5;124m'[39m[38;5;124mpersistent[39m[38;5;124m'[39m:
[0;32m--> 131[0m   credentials [38;5;241m=[39m [43mdata[49m[38;5;241;43m.[39;49m[43mget_persistent_credentials[49m[43m([49m[43m)[49m
[1;32m    132[0m data[38;5;241m.[39minitialize(
[1;32m    133[0m     credentials[38;5;241m=[39mcredentials,
[1;32m    134[0m     api_base_url[38;5;241m=[39m(opt_url [38;5;241m+[39m [38;5;124m'[39m[38;5;124m/api[39m[38;5;124m'[39m [38;5;28;01mif[39;00m opt_url [38;5;28;01melse[39;00m [38;5;28;01mNone[39;00m),
[0;32m   (...)[0m
[1;32m    138[0m     project[38;5;241m=[39mproject,
[1;32m    139[0m     http_transport[38;5;241m=[39mhttp_transport)

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/data.py:223[0m, in [0;36mget_persistent_credentials[0;34m()[0m
[1;32m    222[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIOError[39;00m:
[0;32m--> 223[0m   [38;5;28;01mraise[39;00m ee_exception[38;5;241m.[39mEEException(
[1;32m    224[0m       [38;5;124m'[39m[38;5;124mPlease authorize access to your Earth Engine account by [39m[38;5;124m'[39m
[1;32m    225[0m       [38;5;124m'[39m[38;5;124mrunning[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124mearthengine authenticate[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m'[39m
[1;32m    226[0m       [38;5;124m'[39m[38;5;124min your command line, and then retry.[39m[38;5;124m'[39m)

[0;31mEEException[0m: Please authorize access to your Earth Engine account by running

earthengine authenticate

in your command line, and then retry.

During handling of the above exception, another exception occurred:

[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m Map [38;5;241m=[39m [43mgeemap[49m[38;5;241;43m.[39;49m[43mMap[49m[43m([49m[43mheight[49m[38;5;241;43m=[39;49m[38;5;241;43m800[39;49m[43m,[49m[43mwidth[49m[38;5;241;43m=[39;49m[38;5;241;43m700[39;49m[43m,[49m[43mcenter[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;241;43m52.37[39;49m[43m,[49m[38;5;241;43m4.5[39;49m[43m][49m[43m,[49m[43mzoom[49m[38;5;241;43m=[39;49m[38;5;241;43m7[39;49m[43m)[49m
[1;32m      2[0m Map

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/geemap/geemap.py:52[0m, in [0;36mMap.__init__[0;34m(self, **kwargs)[0m
[1;32m     49[0m     kwargs[[38;5;124m"[39m[38;5;124mee_initialize[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m     51[0m [38;5;28;01mif[39;00m kwargs[[38;5;124m"[39m[38;5;124mee_initialize[39m[38;5;124m"[39m]:
[0;32m---> 52[0m     [43mee_initialize[49m[43m([49m[43m)[49m
[1;32m     54[0m [38;5;66;03m# Default map center location (lat, lon) and zoom level[39;00m
[1;32m     55[0m latlon [38;5;241m=[39m [[38;5;241m20[39m, [38;5;241m0[39m]

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/geemap/common.py:229[0m, in [0;36mee_initialize[0;34m(token_name, auth_mode, service_account)[0m
[1;32m    227[0m     ee[38;5;241m.[39mInitialize(http_transport[38;5;241m=[39mhttplib2[38;5;241m.[39mHttp())
[1;32m    228[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[0;32m--> 229[0m     [43mee[49m[38;5;241;43m.[39;49m[43mAuthenticate[49m[43m([49m[43mauth_mode[49m[38;5;241;43m=[39;49m[43mauth_mode[49m[43m)[49m
[1;32m    230[0m     ee[38;5;241m.[39mInitialize(http_transport[38;5;241m=[39mhttplib2[38;5;241m.[39mHttp())

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/__init__.py:104[0m, in [0;36mAuthenticate[0;34m(authorization_code, quiet, code_verifier, auth_mode, scopes)[0m
[1;32m     78[0m [38;5;28;01mdef[39;00m [38;5;21mAuthenticate[39m(
[1;32m     79[0m     authorization_code[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m     80[0m     quiet[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m     81[0m     code_verifier[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m     82[0m     auth_mode[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m     83[0m     scopes[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m     84[0m   [38;5;124;03m"""Prompts the user to authorize access to Earth Engine via OAuth2.[39;00m
[1;32m     85[0m 
[1;32m     86[0m [38;5;124;03m  Args:[39;00m
[0;32m   (...)[0m
[1;32m    102[0m [38;5;124;03m     (auth_url, code_verifier) when called with quiet='init_only'[39;00m
[1;32m    103[0m [38;5;124;03m  """[39;00m
[0;32m--> 104[0m   [38;5;28;01mreturn[39;00m [43moauth[49m[38;5;241;43m.[39;49m[43mauthenticate[49m[43m([49m[43mauthorization_code[49m[43m,[49m[43m [49m[43mquiet[49m[43m,[49m[43m [49m[43mcode_verifier[49m[43m,[49m[43m [49m[43mauth_mode[49m[43m,[49m
[1;32m    105[0m [43m                            [49m[43mscopes[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/oauth.py:400[0m, in [0;36mauthenticate[0;34m(cli_authorization_code, quiet, cli_code_verifier, auth_mode, scopes)[0m
[1;32m    397[0m [38;5;28;01mif[39;00m flow[38;5;241m.[39mdisplay_instructions(quiet):
[1;32m    398[0m   _open_new_browser(flow[38;5;241m.[39mauth_url)
[0;32m--> 400[0m [43mflow[49m[38;5;241;43m.[39;49m[43msave_code[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/oauth.py:443[0m, in [0;36mFlow.save_code[0;34m(self, code)[0m
[1;32m    441[0m   redirect_uri [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mserver[38;5;241m.[39murl
[1;32m    442[0m   code [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mserver[38;5;241m.[39mfetch_code()  [38;5;66;03m# Waits for oauth callback[39;00m
[0;32m--> 443[0m [43m_obtain_and_write_token[49m[43m([49m[43mcode[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcode_verifier[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mscopes[49m[43m,[49m[43m [49m[43mredirect_uri[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ee/oauth.py:181[0m, in [0;36m_obtain_and_write_token[0;34m(auth_code, code_verifier, scopes, redirect_uri)[0m
[1;32m    179[0m   client_info[[38;5;124m'[39m[38;5;124mredirect_uri[39m[38;5;124m'[39m] [38;5;241m=[39m redirect_uri
[1;32m    180[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m auth_code:
[0;32m--> 181[0m   auth_code [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mEnter verification code: [39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    182[0m [38;5;28;01massert[39;00m [38;5;28misinstance[39m(auth_code, six[38;5;241m.[39mstring_types)
[1;32m    183[0m scopes [38;5;241m=[39m scopes [38;5;129;01mor[39;00m SCOPES

File [0;32m/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/ipykernel/kernelbase.py:1172[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1165[0m [38;5;124;03m"""Forward raw_input to frontends[39;00m
[1;32m   1166[0m 
[1;32m   1167[0m [38;5;124;03mRaises[39;00m
[1;32m   1168[0m [38;5;124;03m------[39;00m
[1;32m   1169[0m [38;5;124;03mStdinNotImplementedError if active frontend doesn't support stdin.[39;00m
[1;32m   1170[0m [38;5;124;03m"""[39;00m
[1;32m   1171[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[0;32m-> 1172[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(
[1;32m   1173[0m         [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[1;32m   1174[0m     )
[1;32m   1175[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1176[0m     [38;5;28mstr[39m(prompt),
[1;32m   1177[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1178[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1179[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1180[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

